### ISSUE TITLE
add context to readme to clearly explain differences between macros

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-audit-helper#61]
### Describe the bug

Currently, the macros have names such that it's difficult to differentiate between them / understand the purpose of each. 

`compare_column_values` - compares a single column's values
`compare_all_columns` - does the same thing as `compare_column_values` but for all columns and only gives the count of records rather than percentages
`compare_relation_columns` - compares the metadata of all columns
I think `compare_column_values_verbose` is the non-summarized view of `compare_column_values` - essentially the same as setting `summarize=false` for the other macros. Why is this it's own macro then?

We should add additional examples to the README showing how to use `compare_all_columns` - both as a test and as a one off query - as well as example outputs.

**Comment by leoebfolsom** [comment]
Hi @graciegoheen ! I agree with what you've written here. I am responsible for `compare_column_values_verbose`, so I'll add a bit of context for that one in particular.

When writing `compare_all_columns`, I _think_ the reason I created `compare_column_values_verbose` was simply so that `compare_all_columns` would be more readable. (Maybe @joellabes remembers something I don't about the reasoning.) You could think of it as an internal or intermediate macro. `compare_all_columns` already is kind of dense, and it would be even more dense if the logic that's currently in `compare_column_values_verbose` were included in the same file.

When we were working on this, I thought that since it was a macro in the package, it should be in the README. However, I never imagined it would be directly used by someone who installed this package, and I wasn't sure what the best practices were around including such macros in the README.

I have no objection to refactoring these into one macro, but I didn't think there was any harm into breaking them up, and I only did so in an attempt to make it all more readable and modular.

Finally, as for more examples:

> We should add additional examples to the README showing how to use compare_all_columns - both as a test and as a one off query - as well as example outputs.

I'm working on a blog post that does exactly this, which I'm hoping to publish later this week, and I'd be more than happy to share the examples I'm creating back as contributions to the README, if that's helpful.
